# https://nimbinatus.com/2019/09/28/pelican-and-ghpages/
# https://github.com/nimbinatus/nimbinatus.github.io/blob/source/.github/workflows/pelican.yml
# https://github.com/JamesIves/github-pages-deploy-action
# https://github.com/actions/setup-python
name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install language packs
      run: sudo apt-get install language-pack-en language-pack-zh-hant language-pack-th
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build site
      run: |
        make download
        make publish
    - name: Add nojekyll
      run: |
        touch ./output/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: output
        CLEAN: true
